/*
 * Meltwater Streaming API v2
 * The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@api.meltwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchemasApi
 */
@Ignore
public class SchemasApiTest {

    private final SchemasApi api = new SchemasApi();

    
    /**
     * Editorial Streaming JSON schema
     *
     * Get the JSON schema describing the layout of Editorial Streaming documents.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEditorialStreamingJsonSchemaTest() throws ApiException {
        String userKey = null;
        api.getEditorialStreamingJsonSchema(userKey);

        // TODO: test validations
    }
    
    /**
     * Social Streaming JSON schema
     *
     * Get the JSON schema describing the layout of Social Streaming documents.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSocialStreamingJsonSchemaTest() throws ApiException {
        String userKey = null;
        api.getSocialStreamingJsonSchema(userKey);

        // TODO: test validations
    }
    
}
