/*
 * Meltwater Streaming API v2
 * The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@api.meltwater.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SwaggerDocApi
 */
@Ignore
public class SwaggerDocApiTest {

    private final SwaggerDocApi api = new SwaggerDocApi();

    
    /**
     * Meltwater API Swagger Spec
     *
     * Get the complete Swagger Spec that describes all Meltwater API endpoints.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompleteSwaggerSpecTest() throws ApiException {
        String userKey = null;
        api.getCompleteSwaggerSpec(userKey);

        // TODO: test validations
    }
    
}
